### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by corneliusellen** [justincanthony/mod_0_assessment#1]
Hi @justincanthony , really nice work on this. I can tell you have a solid understanding of how to model data using objects. I did see one syntax mistake on your Model A for a string datatype - please correct this by the end of Tuesday.

You are officially technical ready. Keep up the hard work moving forward and let me know if you have any questions. As mentioned on the Mod 0 site, we will be reviewing your Mod 1 Prework to determine promotion to Mod 1 - finish strong!

**Comment by justincanthony** [comment]
Hi Ellen.

Thank you for the feedback! I corrected the error , committed the file, and pushed the changes to GitHub. Do I need I need to re-submit my assessment repo to the link provided in the README.md file? 

Best,

Justin Anthony
